import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { ChunkExtractor } from '@loadable/server'
import path from 'path';
import App from '../client/components/App';

const renderer = async (req, res, next) => {
	const remoteEntryScript = `<script src="http://localhost:8081/scripts/remoteEntry.js"></script>`;

	// This is the stats file generated by webpack loadable plugin
	const statsFile = path.resolve(__dirname, '../build/client/loadable-stats.json')
	// We create an extractor from the statsFile
	const extractor = new ChunkExtractor({ statsFile })
	// Wrap your application using "collectChunks"
	const jsx = extractor.collectChunks(<App />)
	// Render your application
	const html = ReactDOMServer.renderToString(jsx)
	// You can now collect your script tags
	const scriptTags = extractor.getScriptTags() // or extractor.getScriptElements();
	// You can also collect your "preload/prefetch" links
	const linkTags = extractor.getLinkTags() // or extractor.getLinkElements();
	// And you can even collect your style tags (if you use "mini-css-extract-plugin")
	const styleTags = extractor.getStyleTags() // or extractor.getStyleElements();

	res.send(`
		<!DOCTYPE html>
		<html lang="en">
			<head>
				<meta charset="UTF-8">
				<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<title>My SSR App</title>
				${remoteEntryScript}
				${linkTags}
				${styleTags}
			</head>
			<body>
				<div id='ssr-app'>${html}</div>
				${scriptTags}
			</body>
		</html>
	`);
};

export default renderer;
